[2024-06-22T11:25:43.698+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_ml_pipeline_class_reg.run_data_wrangling_class_reg manual__2024-06-22T11:25:41.300220+00:00 [queued]>
[2024-06-22T11:25:43.707+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_ml_pipeline_class_reg.run_data_wrangling_class_reg manual__2024-06-22T11:25:41.300220+00:00 [queued]>
[2024-06-22T11:25:43.708+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-06-22T11:25:43.724+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): run_data_wrangling_class_reg> on 2024-06-22 11:25:41.300220+00:00
[2024-06-22T11:25:43.730+0000] {standard_task_runner.py:60} INFO - Started process 1467 to run task
[2024-06-22T11:25:43.734+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'DAG_ml_pipeline_class_reg', 'run_data_wrangling_class_reg', 'manual__2024-06-22T11:25:41.300220+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/run_data_wrangling_class_reg.py', '--cfg-path', '/tmp/tmpl1m5eb9x']
[2024-06-22T11:25:43.737+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask run_data_wrangling_class_reg
[2024-06-22T11:25:43.790+0000] {task_command.py:423} INFO - Running <TaskInstance: DAG_ml_pipeline_class_reg.run_data_wrangling_class_reg manual__2024-06-22T11:25:41.300220+00:00 [running]> on host 0fdcf3d7bc80
[2024-06-22T11:25:43.868+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_ml_pipeline_class_reg' AIRFLOW_CTX_TASK_ID='run_data_wrangling_class_reg' AIRFLOW_CTX_EXECUTION_DATE='2024-06-22T11:25:41.300220+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-22T11:25:41.300220+00:00'
[2024-06-22T11:25:43.870+0000] {logging_mixin.py:188} INFO - Looking for .env file at: /opt/***/config/.env
[2024-06-22T11:25:43.979+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_wrangling_tasks/data_wrangling_class_reg.py", line 40, in main_data_wrangling
    response = s3.list_objects_v2(Bucket=bucket_name, Prefix=f'{prefix}/daily_feed')
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 989, in _make_api_call
    http, parsed_response = self._make_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 1015, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 134, in create_request
    self._event_emitter.emit(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/signers.py", line 195, in sign
    auth.add_auth(request)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
[2024-06-22T11:25:44.002+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=DAG_ml_pipeline_class_reg, task_id=run_data_wrangling_class_reg, execution_date=20240622T112541, start_date=20240622T112543, end_date=20240622T112544
[2024-06-22T11:25:44.018+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task run_data_wrangling_class_reg (Unable to locate credentials; 1467)
[2024-06-22T11:25:44.028+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-06-22T11:25:44.049+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
